### ISSUE TITLE
Update to 2.6.4 request

### ISSUE THREAD

**Issue by joesustaric** [brightbox/deb-ruby2.6#1]
Hi there,
https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-6-4-released/

has some fixes for https://www.ruby-lang.org/en/news/2019/08/28/multiple-jquery-vulnerabilities-in-rdoc/ 

An update would be appreciated.

Thanks!

**Comment by joesustaric** [comment]
might be worth waiting for 2.6.5 as there may be a bug fix https://bugs.ruby-lang.org/issues/16136

**Comment by lucascaton** [comment]
https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/

**Comment by lucascaton** [comment]
Ruby 2.6.5 has been released: https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/

**Comment by johnl** [comment]
Done, 2.6.5 packages released now.
